# Kohnen Self Organizing Map

Problem Statement: Using the Square of Euclidean Distance, find the cluster unit C(j) that is closest to the input vector (0.3,0.4). Using Learning Rate of 0.3, find the new weights for the winning cluster. Find the new weights of C(j-1) and C(j+1) (that is if they exist).

In [62]:
# importing libraries
import numpy as np

In [63]:
# Creating Weight Matrix
w = [[0.2,0.6,0.4,0.9,0.2],[0.3,0.5,0.7,0.6,0.8]]
w = np.array(w)
print(w)

# creating list to hold vectors value
x = [0.3,0.4]
# Storing the value of the learning rate a
a = 0.3

[[0.2 0.6 0.4 0.9 0.2]
 [0.3 0.5 0.7 0.6 0.8]]


In [64]:
# Calculating Euclidean Distance for Each neuron from vectors
d = np.array([0.0]*len(w[0]))

for i in range(len(w)):
    for j in range(len(w[0])):
        d[j] += (w[i][j] - x[i])**2

print(d)

[0.02 0.1  0.1  0.4  0.17]


In [65]:
# Finding the cluster with the minimum distance from the vectors
minV = max(d)
minI = 0

for i in range(len(d)):
    if(minV > d[i]):
        minV = d[i]
        minI = i + 1

print("Winning Cluster is C",minI,"with Euclidean Distance:",minV)

Winning Cluster is C 1 with Euclidean Distance: 0.020000000000000004


In [66]:
# Updating weight for the winning cluster and it's neighbourhood

for i in range(len(w)):
    for j in range(minI-2,minI+1):
        if(j>=0 and j<len(w[0])):
            w[i][j] = w[i][j] + a*(x[i] - w[i][j])

print("Updated Weight Matrix is as follow:")
print(w)

Updated Weight Matrix is as follow:
[[0.23 0.51 0.4  0.9  0.2 ]
 [0.33 0.47 0.7  0.6  0.8 ]]
